/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author michael
 */
public class BuatAkun extends javax.swing.JFrame {

    /**
     * Creates new form Daftar
     */
    public BuatAkun() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        judulLabel = new javax.swing.JLabel();
        borderPanel = new javax.swing.JPanel();
        agamaLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        bankLabel = new javax.swing.JLabel();
        namaLabel = new javax.swing.JLabel();
        namaRekLabel = new javax.swing.JLabel();
        noRekLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        nikLabel = new javax.swing.JLabel();
        ttlLabel = new javax.swing.JLabel();
        nikText = new javax.swing.JTextField();
        namaText = new javax.swing.JTextField();
        passwordText = new javax.swing.JTextField();
        ttlText = new javax.swing.JTextField();
        emailText = new javax.swing.JTextField();
        noRekText = new javax.swing.JTextField();
        namaRekText = new javax.swing.JTextField();
        agamaBox = new javax.swing.JComboBox<>();
        bankBox = new javax.swing.JComboBox<>();
        noTeleponText = new javax.swing.JTextField();
        noTeleponLabel = new javax.swing.JLabel();
        alamatLabel = new javax.swing.JLabel();
        alamatText = new javax.swing.JTextField();
        buatAkunButton = new javax.swing.JButton();
        kembaliButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Buat Akun");

        judulLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        judulLabel.setForeground(new java.awt.Color(102, 153, 255));
        judulLabel.setText("Buat Akun");

        borderPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        borderPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        agamaLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        agamaLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        agamaLabel.setText("Agama :");
        borderPanel.add(agamaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 139, 32));

        emailLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        emailLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        emailLabel.setText("Email :");
        borderPanel.add(emailLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 139, 32));

        bankLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bankLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        bankLabel.setText("Bank :");
        borderPanel.add(bankLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 139, 32));

        namaLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        namaLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        namaLabel.setText("Nama Lengkap :");
        borderPanel.add(namaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 13, 139, 32));

        namaRekLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        namaRekLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        namaRekLabel.setText("Nama Rekening :");
        borderPanel.add(namaRekLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 139, 32));

        noRekLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        noRekLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        noRekLabel.setText("Nomor Rekening :");
        borderPanel.add(noRekLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 139, 32));

        passwordLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        passwordLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        passwordLabel.setText("Password :");
        borderPanel.add(passwordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 99, 139, 32));

        nikLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        nikLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        nikLabel.setText("NIK :");
        borderPanel.add(nikLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 56, 139, 32));

        ttlLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ttlLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        ttlLabel.setText("Tempat, Tanggal Lahir :");
        borderPanel.add(ttlLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 185, 139, 32));
        borderPanel.add(nikText, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 56, 207, 32));

        namaText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaTextActionPerformed(evt);
            }
        });
        borderPanel.add(namaText, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 14, 207, 30));
        borderPanel.add(passwordText, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 99, 207, 32));
        borderPanel.add(ttlText, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 185, 207, 32));
        borderPanel.add(emailText, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, 207, 32));
        borderPanel.add(noRekText, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 390, 207, 32));
        borderPanel.add(namaRekText, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 430, 207, 32));

        agamaBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Islam", "Katolik", "Protestan", "Buddha", "Konghucu", "Hindu" }));
        borderPanel.add(agamaBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, 207, 32));

        bankBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BNI", "BRI", "BTN", "BCA" }));
        borderPanel.add(bankBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 350, 207, 32));
        borderPanel.add(noTeleponText, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 142, 207, 32));

        noTeleponLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        noTeleponLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        noTeleponLabel.setText("No Telepon :");
        borderPanel.add(noTeleponLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 142, 139, 32));

        alamatLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        alamatLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        alamatLabel.setText("Alamat :");
        borderPanel.add(alamatLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 228, 139, 32));
        borderPanel.add(alamatText, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, 207, 32));

        buatAkunButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/BuatAkunButton.png"))); // NOI18N
        buatAkunButton.setText("Buat Akun");
        buatAkunButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buatAkunButtonActionPerformed(evt);
            }
        });

        kembaliButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/KembaliButton.png"))); // NOI18N
        kembaliButton.setText("Kembali");
        kembaliButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembaliButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(borderPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 29, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(kembaliButton, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(judulLabel)
                            .addGap(144, 144, 144))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(buatAkunButton)
                            .addGap(158, 158, 158)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(judulLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(borderPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buatAkunButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kembaliButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void namaTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaTextActionPerformed

    private void kembaliButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembaliButtonActionPerformed
        dispose();
        new Login().setVisible(true);
    }//GEN-LAST:event_kembaliButtonActionPerformed

    private void buatAkunButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buatAkunButtonActionPerformed
        // Pertama cek jika ada kolom TextField yang blm diisi
        if (namaText.getText().equals("") ||
            nikText.getText().equals("") ||
            passwordText.getText().equals("") ||
            noTeleponText.getText().equals("") ||
            ttlText.getText().equals("") ||
            alamatText.getText().equals("") ||
            emailText.getText().equals("") ||
            noRekText.getText().equals("") ||
            namaRekText.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Harap Isi Semua Data");
        }
        else
        {
            try (Connection con = DriverManager
            .getConnection("jdbc:mysql://localhost/uas", "root", ""))
            {
                Statement stat = con.createStatement();
                ResultSet rs = stat.executeQuery("select * from data_karyawan "
                        + "where NIK = '" + nikText.getText() + "'");
                // Cek jika NIK sudah ada sebelumnya
                if (rs.next())
                {
                    JOptionPane.showMessageDialog(null, "NIK \"" + nikText.getText() 
                            + "\" Sudah Ada");
                }
                else
                {
                    // Sudah tidak ada masalah, masukkan data ke database
                    stat.executeUpdate("INSERT INTO `data_karyawan` "
                            + "(`Nama`, `NIK`, `Password`, `No Telepon`, `TTL`, "
                            + "`Alamat`, `Agama`, `Email`, `Bank`, `No Rekening`,"
                            + " `Nama Rekening`) "
                            + "VALUES ("
                            + "'" + namaText.getText() + "', "
                            + "'" + nikText.getText() + "', "
                            + "'" + passwordText.getText() + "', "
                            + "'" + noTeleponText.getText() + "', "
                            + "'" + ttlText.getText() + "', "
                            + "'" + alamatText.getText() + "', "
                            + "'" + (String)agamaBox.getSelectedItem() + "', "
                            + "'" + emailText.getText() + "', "
                            + "'" + (String)bankBox.getSelectedItem() + "', "
                            + "'" + noRekText.getText() + "', "
                            + "'" + namaRekText.getText() + "');"
                    );
                    JOptionPane.showMessageDialog(null, "Akun Berhasil Didaftarkan");
                    dispose();
                    new Login().setVisible(true);
                }  
                
            } catch (SQLException e) {
                System.out.println(e);
            }
        }
    }//GEN-LAST:event_buatAkunButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuatAkun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuatAkun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuatAkun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuatAkun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BuatAkun().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> agamaBox;
    private javax.swing.JLabel agamaLabel;
    private javax.swing.JLabel alamatLabel;
    private javax.swing.JTextField alamatText;
    private javax.swing.JComboBox<String> bankBox;
    private javax.swing.JLabel bankLabel;
    private javax.swing.JPanel borderPanel;
    private javax.swing.JButton buatAkunButton;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField emailText;
    private javax.swing.JLabel judulLabel;
    private javax.swing.JButton kembaliButton;
    private javax.swing.JLabel namaLabel;
    private javax.swing.JLabel namaRekLabel;
    private javax.swing.JTextField namaRekText;
    private javax.swing.JTextField namaText;
    private javax.swing.JLabel nikLabel;
    private javax.swing.JTextField nikText;
    private javax.swing.JLabel noRekLabel;
    private javax.swing.JTextField noRekText;
    private javax.swing.JLabel noTeleponLabel;
    private javax.swing.JTextField noTeleponText;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JTextField passwordText;
    private javax.swing.JLabel ttlLabel;
    private javax.swing.JTextField ttlText;
    // End of variables declaration//GEN-END:variables
}
