package View;

import Control.LoginInfo;
import javax.swing.*;
import java.awt.*;

public class MainMenu extends javax.swing.JFrame {

    public MainMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainMenuLabel = new javax.swing.JLabel();
        MenuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        myProfileMenuItem = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        daftarServiceMenuItem = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        signOutMenuItem = new javax.swing.JMenuItem();
        buatMenu = new javax.swing.JMenu();
        transaksiBaruMenuItem = new javax.swing.JMenuItem();
        laporanMenu = new javax.swing.JMenu();
        daftarTransaksiMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Utama");

        mainMenuLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/MainMenuLabel.jpg"))); // NOI18N

        MenuBar.setBackground(new java.awt.Color(255, 255, 255));

        fileMenu.setText("File");

        myProfileMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        myProfileMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/BuatAkunButton_2.png"))); // NOI18N
        myProfileMenuItem.setText("My Profile");
        myProfileMenuItem.setToolTipText("");
        myProfileMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myProfileMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(myProfileMenuItem);
        fileMenu.add(jSeparator1);

        daftarServiceMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        daftarServiceMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/DaftarServiceMenuItem.png"))); // NOI18N
        daftarServiceMenuItem.setText("Daftar Service");
        daftarServiceMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                daftarServiceMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(daftarServiceMenuItem);
        fileMenu.add(jSeparator2);

        signOutMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        signOutMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/KeluarButton.png"))); // NOI18N
        signOutMenuItem.setText("Sign Out");
        signOutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signOutMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(signOutMenuItem);

        MenuBar.add(fileMenu);

        buatMenu.setText("Buat");

        transaksiBaruMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        transaksiBaruMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/TransaksiBaruMenuItem.png"))); // NOI18N
        transaksiBaruMenuItem.setText("Transaksi Baru");
        transaksiBaruMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transaksiBaruMenuItemActionPerformed(evt);
            }
        });
        buatMenu.add(transaksiBaruMenuItem);

        MenuBar.add(buatMenu);

        laporanMenu.setText("Laporan");

        daftarTransaksiMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        daftarTransaksiMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/DaftarTransaksiMenuItem.png"))); // NOI18N
        daftarTransaksiMenuItem.setText("Daftar Transaksi");
        daftarTransaksiMenuItem.setToolTipText("");
        daftarTransaksiMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                daftarTransaksiMenuItemActionPerformed(evt);
            }
        });
        laporanMenu.add(daftarTransaksiMenuItem);

        MenuBar.add(laporanMenu);

        setJMenuBar(MenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainMenuLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainMenuLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void signOutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signOutMenuItemActionPerformed
        LoginInfo.NIK = "";
        dispose();
        new Login().setVisible(true);
    }//GEN-LAST:event_signOutMenuItemActionPerformed

    private void myProfileMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myProfileMenuItemActionPerformed
        dispose();
        new Profile().setVisible(true);
    }//GEN-LAST:event_myProfileMenuItemActionPerformed

    private void daftarServiceMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_daftarServiceMenuItemActionPerformed
        dispose();
        new DaftarService().setVisible(true);
    }//GEN-LAST:event_daftarServiceMenuItemActionPerformed

    private void transaksiBaruMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transaksiBaruMenuItemActionPerformed
        dispose();
        new BuatTransaksi().setVisible(true);
    }//GEN-LAST:event_transaksiBaruMenuItemActionPerformed

    private void daftarTransaksiMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_daftarTransaksiMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_daftarTransaksiMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.JMenu buatMenu;
    private javax.swing.JMenuItem daftarServiceMenuItem;
    private javax.swing.JMenuItem daftarTransaksiMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JMenu laporanMenu;
    private javax.swing.JLabel mainMenuLabel;
    private javax.swing.JMenuItem myProfileMenuItem;
    private javax.swing.JMenuItem signOutMenuItem;
    private javax.swing.JMenuItem transaksiBaruMenuItem;
    // End of variables declaration//GEN-END:variables
}
